version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      go-modules:
        patterns:
          - "*"
    pull-request-title:
      prefix: "chore(deps)"
      separator: " "
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      actions-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"
    pull-request-title:
      prefix: "chore(deps-dev)"
      separator: " "
    labels:
      - "dependencies"
      - "github-actions"
