# Build the manager binary
FROM registry.redhat.io/ubi9/go-toolset:9.8-1791479310@sha256:8a523f9109ce1b18d2d83be3da4aa5d86191fc7b03a93605687117bf1a90d0db AS builder
ARG TARGETOS
ARG TARGETARCH
ARG AGENT_IMG

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY cmd/main.go cmd/main.go
COPY api/ api/
COPY internal/ internal/

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a \
    -ldflags="-X github.com/sigstore/model-validation-operator/internal/constants.ModelValidationAgentImage=${AGENT_IMG}" \
    -o manager cmd/main.go

# Use minimal base image to package the manager binary
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:5ed244b62bbf4095080144d9d35eb8fcd3d39a9801f94aadd63b9d10978a01ae
WORKDIR /
COPY --from=builder /workspace/manager .
USER 65532:65532

LABEL description="The image for the model-validation operator."
LABEL io.k8s.description="The image for the model-validation operator."
LABEL io.k8s.display-name="Model validation operator container image for Red Hat Trusted Artifact Signer."
LABEL io.openshift.tags="model-validation, Red Hat Trusted Artifact Signer."
LABEL summary="Operator for the model-validation operator."
LABEL com.redhat.component="model-validation-operator"
LABEL name="rhtas/model-validation-rhel9-operator"

ENTRYPOINT ["/manager"]
