# Build the manager binary
FROM registry.redhat.io/ubi9/go-toolset:9.7-1774351791@sha256:7f4d4708bb41f24b2589a76aea8d2b359c9079b4c18c8fb026d036a231c2b8be AS builder
ARG TARGETOS
ARG TARGETARCH
ARG AGENT_IMG

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY cmd/main.go cmd/main.go
COPY api/ api/
COPY internal/ internal/

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a \
    -ldflags="-X github.com/sigstore/model-validation-operator/internal/constants.ModelValidationAgentImage=${AGENT_IMG}" \
    -o manager cmd/main.go

# Use minimal base image to package the manager binary
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:83006d535923fcf1345067873524a3980316f51794f01d8655be55d6e9387183
WORKDIR /
COPY --from=builder /workspace/manager .
USER 65532:65532

LABEL description="The image for the model-validation operator."
LABEL io.k8s.description="The image for the model-validation operator."
LABEL io.k8s.display-name="Model validation operator container image for Red Hat Trusted Artifact Signer."
LABEL io.openshift.tags="model-validation, Red Hat Trusted Artifact Signer."
LABEL summary="Operator for the model-validation operator."
LABEL com.redhat.component="model-validation-operator"
LABEL name="rhtas/model-validation-rhel9-operator"

ENTRYPOINT ["/manager"]
