# Build the validation-agent binary
FROM registry.redhat.io/ubi9/go-toolset:9.8-1790174511@sha256:0a4666f7a4eb0644c97a73cba198eb268691b270d97831822689e7a2088f87be AS agent-builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/validation-agent/ cmd/validation-agent/
COPY internal/ internal/
COPY api/ api/

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} \
    go build -a -o validation-agent cmd/validation-agent/main.go

# Use minimal base image to package the validation-agent binary
FROM registry.access.redhat.com/ubi9-minimal@sha256:1d7c5517a4a1a8e2688620b39ee980e82505ca1ab7ae5541b5463120ae9b3897

WORKDIR /

COPY --from=agent-builder /workspace/validation-agent /usr/local/bin/

USER 65532:65532

LABEL description="The image for the model-validation agent."
LABEL io.k8s.description="The image for the model-validation agent."
LABEL io.k8s.display-name="Model validation agent container image for Red Hat Trusted Artifact Signer."
LABEL io.openshift.tags="model-validation-agent, Red Hat Trusted Artifact Signer."
LABEL summary="Validation agent for the model-validation operator."
LABEL com.redhat.component="model-validation-agent"
LABEL name="rhtas/model-validation-agent-rhel9"

ENTRYPOINT ["/usr/local/bin/validation-agent"]
