# Build the manager binary
FROM registry.redhat.io/ubi9/go-toolset:9.7-1775724628@sha256:a5c9eaea7dd305d0c79a0ff5c620c1c7a0cff87335684ae216205faca70458f3 AS builder
ARG TARGETOS
ARG TARGETARCH
ARG AGENT_IMG

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY cmd/main.go cmd/main.go
COPY api/ api/
COPY internal/ internal/

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a \
    -ldflags="-X github.com/sigstore/model-validation-operator/internal/constants.ModelValidationAgentImage=${AGENT_IMG}" \
    -o manager cmd/main.go

# Use minimal base image to package the manager binary
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:d91be7cea9f03a757d69ad7fcdfcd7849dba820110e7980d5e2a1f46ed06ea3b
WORKDIR /
COPY --from=builder /workspace/manager .
USER 65532:65532

LABEL description="The image for the model-validation operator."
LABEL io.k8s.description="The image for the model-validation operator."
LABEL io.k8s.display-name="Model validation operator container image for Red Hat Trusted Artifact Signer."
LABEL io.openshift.tags="model-validation, Red Hat Trusted Artifact Signer."
LABEL summary="Operator for the model-validation operator."
LABEL com.redhat.component="model-validation-operator"
LABEL name="rhtas/model-validation-rhel9-operator"

ENTRYPOINT ["/manager"]
