---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ml.sigstore.dev
  resources:
  - modelvalidations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ml.sigstore.dev
  resources:
  - modelvalidations/status
  verbs:
  - get
  - patch
  - update
