---
apiVersion: ml.sigstore.dev/v1alpha1
kind: ModelValidation
metadata:
  name: example
spec:
  config:
    # pkiConfig:
    #   certificateAuthority: /path/to/ca.crt
    publicKeyConfig:
      keyPath: /root/pub.key
    # sigstoreConfig:
    #   certificateIdentity: "https://sigstore.example.com/certificate"
    #   certificateOidcIssuer: "https://issuer.example.com/oidc"
  model:
    path: /root/.ollama/models/gemma2/2b
    signaturePath: /root/.ollama/models/gemma2/2b.sig
---
apiVersion: v1
kind: Pod
metadata:
  name: ollama
  labels:
    validation.ml.sigstore.dev/ml: "example"
spec:
  containers:
  - name: ollama
    image: ollama/ollama
    ports:
    - containerPort: 11434
