apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/securesign/model-validation-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: model-validation-operator
    appstudio.openshift.io/component: model-validation-operator-bundle
    pipelines.appstudio.openshift.io/type: build
  name: model-validation-operator-bundle-on-pull-request
  namespace: rhtas-tenant
spec:
  params:
  - name: release-version
    value: "1.4.2"
  - name: image-version
    value: "0.1.1"
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/securesign/model-validation-operator-bundle:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: Dockerfile.model-validation-bundle.rh
  - name: path-context
    value: .
  - name: hermetic
    value: "true"
  - name: build-source-image
    value: "true"
  - name: manager-pipelinerun-selector
    value: "appstudio.openshift.io/application=model-validation-operator,appstudio.openshift.io/component=model-validation-operator,pipelinesascode.tekton.dev/sha={{revision}},pipelinesascode.tekton.dev/event-type in (pull_request,retest-all-comment)"
  - name: manager-registry-url
    value: registry.redhat.io/rhtas/model-validation-rhel9-operator
  pipelineRef:
    params:
    - name: url
      value: https://github.com/securesign/pipelines.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/bundle-build-oci-ta.yaml
    resolver: git
  taskRunTemplate:
    serviceAccountName: build-pipeline-model-validation-operator-bundle
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
