name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6

      - name: Setup Go
        uses: actions/setup-go@def8c394e3ad351a79bc93815e4a585520fe993b # v5
        with:
          go-version-file: go.mod

      - name: Running Tests
        run: |
          make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          files: cover.out
          flags: unit
          use_oidc: true
          fail_ci_if_error: true
          skip_validation: true
