name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-e2e:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Create kind cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: kind

      - name: Wait for kind cluster to be ready
        run: |
          kubectl wait --for=condition=Ready nodes --all --timeout=300s
          kubectl wait --for=condition=Ready --namespace=kube-system pod --all --timeout=300s
          echo "Cluster is ready"

      - name: Run E2E tests
        run: |
          make test-e2e-ci
